name: Check linting

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  Check-flake8:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      - name: Get Diff Action
        uses: technote-space/get-diff-action@v4.0.1
        with:
          PATTERNS: cleaning_app/**/*.py

      -
        name: flake8
        run: flake8 ${{ env.GIT_DIFF_FILTERED }}
        if: env.GIT_DIFF_FILTERED
      
  Check-black:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      - name: Get Diff Action
        uses: technote-space/get-diff-action@v4.0.1
        with:
          PATTERNS: cleaning_app/**/*.py

      -
        name: black
        run: black ${{ env.GIT_DIFF_FILTERED }} --check
        if: env.GIT_DIFF_FILTERED
